# ==================================================================================
#       Copyright (c) 2019 Nokia
#       Copyright (c) 2018-2019 AT&T Intellectual Property.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#          http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# ==================================================================================
FROM python:3.7-alpine

# copy NNG and rmr out of the  CI builder nng
# NOTE: rmr-pythons documentation does not change based on what version of rmr is installed, only based on what version rmr-python was built (coding wise) against last, so it doesn't matter if the rmr in the parent repo here is ahead
COPY --from=nexus3.o-ran-sc.org:10004/bldr-alpine3:3-a3.9 /usr/local/lib64/libnng.so /usr/local/lib64/libnng.so
COPY --from=nexus3.o-ran-sc.org:10004/bldr-alpine3:3-a3.9 /usr/local/lib64/librmr_nng.so /usr/local/lib64/librmr_nng.so

COPY rmr/ /tmp/rmr
COPY docs/ /tmp/docs
WORKDIR /tmp

# Gevent needs gcc; TODO: this will get fixed
#RUN apk add gcc musl-dev
RUN apk add --update make

# do the actual install; this writes into /usr/local, need root
#RUN pip install .
RUN pip install sphinx numpydoc

WORKDIR /tmp/docs/
ENV LD_LIBRARY_PATH /usr/local/lib/:/usr/local/lib64
# text generates the documentation in text format
CMD make text
