#
#==================================================================================
#       Copyright (c) 2019 Nokia
#       Copyright (c) 2018-2019 AT&T Intellectual Property.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#==================================================================================
#

To build the rtm_sim application, the expected CMake "process" is followed
and described below:

	mkdir .build
	cd .build
	cmake ..
	make package


This will generate at least a .deb, and if the underlying system can support
it an RPM package as well.


Once installed, the rtm_sim application can be started from the command line:
	rtm_sim config-file-name

The config file defines the table(s) which are to be constructed and distributed
to applications.

